version: "3"

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: restart
    container_name: nginx
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "nginx-proxy-manager-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${DB_USER}"
      DB_MYSQL_PASSWORD: "${DB_PASS}"
      DB_MYSQL_NAME: "${DB_NAME}"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ~/nginx_data:/data
      - ~/nginnx_letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  nginx-db:
    image: 'jc21/mariadb-aria:latest'
    restart: restart
    container_name: nginx-db
    environment:
      MYSQL_ROOT_PASSWORD: "${ROOT_PASS}"
      MYSQL_DATABASE: "${DB_USER}"
      MYSQL_USER: "${DB_PASS}"
      MYSQL_PASSWORD: "${DB_NAME}"
    volumes:
      - ~/nginx_db_data/mysql:/var/lib/mysql

networks:
  default:
    external: true
    name: front